name: Quality Gateway

on: [push]

# run go tests
jobs:
  quality-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.23.2

      - name: Run tests
        run: go test ./...

      - name: Run mod verify
        run: go mod verify

      - name: Test build
        run: go build . && ./pkg

      - name: Test package install (local)
        run: go install . && pkg

      - name: Test package install (remote)
        run: go install -u github.com/marco-souza/pkg@latest && pkg

